version: '3'

networks:
  sample_bank:

services:
  account_manager:
    container_name: account_manager
    build:
      context: ./backend/account-manager
    command: npm start
    ports:
      - 4000:4000
    environment:
      - NODE_ENV=dev
      - PORT=4000
      - DB_HOST=postgres
      - DB_USER=user
      - DB_PASSWORD=pass
      - DB_NAME=db
    networks:
      - sample_bank
    depends_on:
      - postgres
 
  branch_finder:
    container_name: branch_finder
    build:
      context: ./backend/branch-finder
    command: npm start
    ports:
      - 4010:4010
    environment:
      - NODE_ENV=dev
      - DB_CONN_STR=mongodb://mongodb:27017/samplebank
      - PORT=4010
    networks:
      - sample_bank
    depends_on:
      - mongodb

  plan_simulator:
    container_name: plan_simulator
    build:
      context: ./backend/plan-simulator
    command: npm start
    ports:
      - 4020:4020
    environment:
      - NODE_ENV=dev
      - PORT=4020
      - DB_HOST=postgres
      - DB_USER=user
      - DB_PASSWORD=pass
      - DB_NAME=db
    networks:
      - sample_bank
    depends_on:
      - postgres

  frontend:
    container_name: frontend
    build: ./frontend
    command: npm start
    ports:
      - 5000:5000
    environment:
      - REACT_APP_ACCOUNT_MANAGER_API=http://localhost:4000/api/v1
      - REACT_APP_PLAN_SIMULATOR_API=http://localhost:4020/api/v1
      - REACT_APP_BRANCH_FINDER_API=http://localhost:4010/api/v1
    networks:
      - sample_bank
    depends_on:
      - account_manager

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - sample_bank
    volumes: 
      - mongodata:/data/db

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    networks:
      - sample_bank
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
  mongodata:
    driver: local
