/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:8f5cfab9-fb38-42b2-8740-910b98f8c381",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_HjdATiebQ",
    "aws_user_pools_web_client_id": "4oe9ii3vdjpl33dprir84lfci7",
    "oauth": {}
};


export default awsmobile;
