name: deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Build React App
        run: cd frontend && npm install && npm run build
      - name: Deploy app build to S3 bucket
        run: aws s3 sync frontend/build/ s3://amirelemam.com --delete --acl public-read
      - name: Install VPC Plugin and Deploy
        uses: serverless/github-action@v1.53.0
        with:
        args: -c "cd services/account-manager && serverless plugin install --name serverless-vpc-discovery && serverless deploy --stage=dev --verbose"
        entrypoint: /bin/bash
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SLS_DEBUG: 1